#!/bin/bash

OBJ=("OBJ")
while IFS= read -r -d '' DIR;
do
    OBJ+=("${DIR//" "/"\ "}")
done < <(find . \( ! -regex '.*/\..*' \) -type d -name "$*" -print0 2>/dev/null)

if [ "$#" -lt 1 ] || [ $0 != "-bash" ]; then
    echo "Usage: . ccd <dir_name>"
else
    if [ "${#OBJ[@]}" == 1 ]; then
        while IFS= read -r -d '' DIR;
        do
            OBJ+=("${DIR//" "/"\ "}")
        done < <(find $HOME \( ! -regex '.*/\..*' \) -type d -name "$*" -print0 2>/dev/null)
    fi
    if [ "${#OBJ[@]}" == 2 ]; then
        eval eval cd "${OBJ[1]}"
    elif [ "${#OBJ[@]}" -gt 2 ]; then
        for ((i=1; i<${#OBJ[@]}; i++)); do
            printf "$i) ${OBJ[$i]}\n"
        done
        ENTRY="-1"
        until [ \( "$ENTRY" -gt 0 \) -a \( "$ENTRY" -lt ${#OBJ[@]} \) ]
        do
            read ENTRY
        done
        eval eval cd "${OBJ[$ENTRY]}"
    else
        echo "$*: No such file or directory."
    fi
fi
