#!/bin/bash

local OBJ
while IFS= read -r -d '' DIR;
do
    OBJ+=("${DIR//" "/"\ "}")
done < <(find . \( ! -regex '.*/\..*' \) -type d -name "$*" -print0 2>/dev/null)

if [ "$#" -lt 1 ] || [ $0 != "-bash" ]; then
    echo "Usage: . ccd <dir_name>"
else
    if [ "${#OBJ[@]}" == 0 ]; then
        while IFS= read -r -d '' DIR;
        do
            OBJ+=("${DIR//" "/"\ "}")
        done < <(find $HOME \( ! -regex '.*/\..*' \) -type d -name "$*" -print0 2>/dev/null)
    fi
    if [ "${#OBJ[@]}" == 1 ]; then
        eval cd "${OBJ[0]}"
    elif [ "${#OBJ[@]}" -gt 1 ]; then
        for ((i=0; i<${#OBJ[@]}; i++)); do
            printf "$((i+1))) ${OBJ[$i]}\n"
        done
        local ENTRY="-1"
        until [ \( "$ENTRY" -gt 0 \) -a \( "$ENTRY" -le ${#OBJ[@]} \) ]
        do
            read ENTRY
        done
        eval cd "${OBJ[$((ENTRY-1))]}"
    else
        echo "$*: No such file or directory."
    fi
fi
