#!/bin/bash

DIR="$*"
OBJ=("OBJ")
while IFS= read -r -d '' DIR;
do
    OBJ+=("${DIR//" "/"\ "}")
done < <(find . \( ! -regex '.*/\..*' \) -type d -name "$DIR" -print0 2>/dev/null)

if [ "$#" -lt 1 ] || [ \( $0 != "bash" \) -a \( $0 != "-bash" \) ]; then
    echo "Usage: . ccd <dir_name>"
else
    if [ "${#OBJ[@]}" == 0 ]; then
        while IFS= read -r -d '' DIR;
        do
            OBJ+=("${DIR//" "/"\ "}")
        done < <(find . \( ! -regex '.*/\..*' \) -type d -name "$DIR" -print0 2>/dev/null)
    fi
    if [ "${#OBJ[@]}" == 2 ]; then
        eval cd "${OBJ[1]}"
    elif [ "${#OBJ[@]}" -gt 2 ]; then
        for ((i=1; i<${#OBJ[@]}; i++)); do
            OBJ[$i]="${OBJ[i]}"
            printf "$i) ${OBJ[$i]}\n"
        done
        read ENTRY
        until [ \( "$ENTRY" -gt 0 \) -a \( "$ENTRY" -le ${#OBJ[@]} \) ]
        do
            read ENTRY
        done
        eval cd "${OBJ[$ENTRY]}"
    else
        echo "$DIR: No such file or directory."
    fi
fi
