#!/bin/bash

local OBJ
mapfile -t OBJ < <(find . \( ! -regex '.*/\..*' \) -type d -name "$*" 2>/dev/null)

if [ "$#" == 0 ] || [ \( $0 != "bash" \) -a \( $0 != "-bash" \) ]; then
    echo "Usage: . ccd <dir_name>"
else
    if [ "${#OBJ[@]}" == 0 ]; then
        mapfile -t OBJ < <(find ~ \( ! -regex '.*/\..*' \) -type d -name "$*" 2>/dev/null)
    fi
    if [ "${#OBJ[@]}" == 1 ]; then
        eval cd "${OBJ[0]//" "/"\ "}"
    elif [ "${#OBJ[@]}" -gt 1 ]; then
        for ((i=0; i<${#OBJ[@]}; i++)); do
            OBJ[$i]="${OBJ[i]//" "/"\ "}"
            printf "$((i+1))) ${OBJ[$i]}\n"
        done
        read ENTRY
        until [ \( "$ENTRY" -gt 0 \) -a \( "$ENTRY" -le ${#OBJ[@]} \) ]
        do
            read ENTRY
        done
        eval cd "${OBJ[$((ENTRY-1))]}"
    else
        echo "$*: No such file or directory."
    fi
fi
